apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: cistanas

patches:
  - target:
      kind: PersistentVolumeClaim
      name: cistanas-data
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: cistanas-data
      spec:
        storageClassName: pd-ssd
        resources:
          requests:
            storage: 20Gi

  - target:
      kind: Deployment
      name: cistanas
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cistanas
      spec:
        template:
          spec:
            containers:
              - name: cistanas
                env:
                  - name: CistaNas__Storage__Provider
                    value: gcs
                  - name: CistaNas__Storage__BucketOrContainer
                    valueFrom:
                      secretKeyRef:
                        name: cistanas-secrets
                        key: CistaNas__Storage__BucketOrContainer
                        optional: true
                  - name: CistaNas__Storage__VolumeDataPath
                    value: /app/data
                resources:
                  limits:
                    memory: 1Gi
                  requests:
                    memory: 256Mi

# GKE Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cistanas
  namespace: cistanas
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: cistanas-ip
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cistanas
                port:
                  number: 80
